// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package v3

import (
	"context"
	"sync"

	"github.com/rancher/norman/controller"
	"github.com/rancher/norman/objectclient"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
)

var (
	lockLdapConfigListerMockGet  sync.RWMutex
	lockLdapConfigListerMockList sync.RWMutex
)

// Ensure, that LdapConfigListerMock does implement LdapConfigLister.
// If this is not the case, regenerate this file with moq.
var _ LdapConfigLister = &LdapConfigListerMock{}

// LdapConfigListerMock is a mock implementation of LdapConfigLister.
//
//     func TestSomethingThatUsesLdapConfigLister(t *testing.T) {
//
//         // make and configure a mocked LdapConfigLister
//         mockedLdapConfigLister := &LdapConfigListerMock{
//             GetFunc: func(namespace string, name string) (*LdapConfig, error) {
// 	               panic("mock out the Get method")
//             },
//             ListFunc: func(namespace string, selector labels.Selector) ([]*LdapConfig, error) {
// 	               panic("mock out the List method")
//             },
//         }
//
//         // use mockedLdapConfigLister in code that requires LdapConfigLister
//         // and then make assertions.
//
//     }
type LdapConfigListerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespace string, name string) (*LdapConfig, error)

	// ListFunc mocks the List method.
	ListFunc func(namespace string, selector labels.Selector) ([]*LdapConfig, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Selector is the selector argument value.
			Selector labels.Selector
		}
	}
}

// Get calls GetFunc.
func (mock *LdapConfigListerMock) Get(namespace string, name string) (*LdapConfig, error) {
	if mock.GetFunc == nil {
		panic("LdapConfigListerMock.GetFunc: method is nil but LdapConfigLister.Get was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockLdapConfigListerMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockLdapConfigListerMockGet.Unlock()
	return mock.GetFunc(namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedLdapConfigLister.GetCalls())
func (mock *LdapConfigListerMock) GetCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockLdapConfigListerMockGet.RLock()
	calls = mock.calls.Get
	lockLdapConfigListerMockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *LdapConfigListerMock) List(namespace string, selector labels.Selector) ([]*LdapConfig, error) {
	if mock.ListFunc == nil {
		panic("LdapConfigListerMock.ListFunc: method is nil but LdapConfigLister.List was just called")
	}
	callInfo := struct {
		Namespace string
		Selector  labels.Selector
	}{
		Namespace: namespace,
		Selector:  selector,
	}
	lockLdapConfigListerMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockLdapConfigListerMockList.Unlock()
	return mock.ListFunc(namespace, selector)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedLdapConfigLister.ListCalls())
func (mock *LdapConfigListerMock) ListCalls() []struct {
	Namespace string
	Selector  labels.Selector
} {
	var calls []struct {
		Namespace string
		Selector  labels.Selector
	}
	lockLdapConfigListerMockList.RLock()
	calls = mock.calls.List
	lockLdapConfigListerMockList.RUnlock()
	return calls
}

var (
	lockLdapConfigControllerMockAddClusterScopedHandler sync.RWMutex
	lockLdapConfigControllerMockAddHandler              sync.RWMutex
	lockLdapConfigControllerMockEnqueue                 sync.RWMutex
	lockLdapConfigControllerMockGeneric                 sync.RWMutex
	lockLdapConfigControllerMockInformer                sync.RWMutex
	lockLdapConfigControllerMockLister                  sync.RWMutex
	lockLdapConfigControllerMockStart                   sync.RWMutex
	lockLdapConfigControllerMockSync                    sync.RWMutex
)

// Ensure, that LdapConfigControllerMock does implement LdapConfigController.
// If this is not the case, regenerate this file with moq.
var _ LdapConfigController = &LdapConfigControllerMock{}

// LdapConfigControllerMock is a mock implementation of LdapConfigController.
//
//     func TestSomethingThatUsesLdapConfigController(t *testing.T) {
//
//         // make and configure a mocked LdapConfigController
//         mockedLdapConfigController := &LdapConfigControllerMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, handler LdapConfigHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, handler LdapConfigHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             EnqueueFunc: func(namespace string, name string)  {
// 	               panic("mock out the Enqueue method")
//             },
//             GenericFunc: func() controller.GenericController {
// 	               panic("mock out the Generic method")
//             },
//             InformerFunc: func() cache.SharedIndexInformer {
// 	               panic("mock out the Informer method")
//             },
//             ListerFunc: func() LdapConfigLister {
// 	               panic("mock out the Lister method")
//             },
//             StartFunc: func(ctx context.Context, threadiness int) error {
// 	               panic("mock out the Start method")
//             },
//             SyncFunc: func(ctx context.Context) error {
// 	               panic("mock out the Sync method")
//             },
//         }
//
//         // use mockedLdapConfigController in code that requires LdapConfigController
//         // and then make assertions.
//
//     }
type LdapConfigControllerMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, handler LdapConfigHandlerFunc)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, handler LdapConfigHandlerFunc)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(namespace string, name string)

	// GenericFunc mocks the Generic method.
	GenericFunc func() controller.GenericController

	// InformerFunc mocks the Informer method.
	InformerFunc func() cache.SharedIndexInformer

	// ListerFunc mocks the Lister method.
	ListerFunc func() LdapConfigLister

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, threadiness int) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler LdapConfigHandlerFunc
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Handler is the handler argument value.
			Handler LdapConfigHandlerFunc
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Generic holds details about calls to the Generic method.
		Generic []struct {
		}
		// Informer holds details about calls to the Informer method.
		Informer []struct {
		}
		// Lister holds details about calls to the Lister method.
		Lister []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threadiness is the threadiness argument value.
			Threadiness int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *LdapConfigControllerMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, handler LdapConfigHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("LdapConfigControllerMock.AddClusterScopedHandlerFunc: method is nil but LdapConfigController.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     LdapConfigHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockLdapConfigControllerMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockLdapConfigControllerMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, handler)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedLdapConfigController.AddClusterScopedHandlerCalls())
func (mock *LdapConfigControllerMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Handler     LdapConfigHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     LdapConfigHandlerFunc
	}
	lockLdapConfigControllerMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockLdapConfigControllerMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *LdapConfigControllerMock) AddHandler(ctx context.Context, name string, handler LdapConfigHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("LdapConfigControllerMock.AddHandlerFunc: method is nil but LdapConfigController.AddHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Handler LdapConfigHandlerFunc
	}{
		Ctx:     ctx,
		Name:    name,
		Handler: handler,
	}
	lockLdapConfigControllerMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockLdapConfigControllerMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, handler)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedLdapConfigController.AddHandlerCalls())
func (mock *LdapConfigControllerMock) AddHandlerCalls() []struct {
	Ctx     context.Context
	Name    string
	Handler LdapConfigHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Handler LdapConfigHandlerFunc
	}
	lockLdapConfigControllerMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockLdapConfigControllerMockAddHandler.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *LdapConfigControllerMock) Enqueue(namespace string, name string) {
	if mock.EnqueueFunc == nil {
		panic("LdapConfigControllerMock.EnqueueFunc: method is nil but LdapConfigController.Enqueue was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockLdapConfigControllerMockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	lockLdapConfigControllerMockEnqueue.Unlock()
	mock.EnqueueFunc(namespace, name)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//     len(mockedLdapConfigController.EnqueueCalls())
func (mock *LdapConfigControllerMock) EnqueueCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockLdapConfigControllerMockEnqueue.RLock()
	calls = mock.calls.Enqueue
	lockLdapConfigControllerMockEnqueue.RUnlock()
	return calls
}

// Generic calls GenericFunc.
func (mock *LdapConfigControllerMock) Generic() controller.GenericController {
	if mock.GenericFunc == nil {
		panic("LdapConfigControllerMock.GenericFunc: method is nil but LdapConfigController.Generic was just called")
	}
	callInfo := struct {
	}{}
	lockLdapConfigControllerMockGeneric.Lock()
	mock.calls.Generic = append(mock.calls.Generic, callInfo)
	lockLdapConfigControllerMockGeneric.Unlock()
	return mock.GenericFunc()
}

// GenericCalls gets all the calls that were made to Generic.
// Check the length with:
//     len(mockedLdapConfigController.GenericCalls())
func (mock *LdapConfigControllerMock) GenericCalls() []struct {
} {
	var calls []struct {
	}
	lockLdapConfigControllerMockGeneric.RLock()
	calls = mock.calls.Generic
	lockLdapConfigControllerMockGeneric.RUnlock()
	return calls
}

// Informer calls InformerFunc.
func (mock *LdapConfigControllerMock) Informer() cache.SharedIndexInformer {
	if mock.InformerFunc == nil {
		panic("LdapConfigControllerMock.InformerFunc: method is nil but LdapConfigController.Informer was just called")
	}
	callInfo := struct {
	}{}
	lockLdapConfigControllerMockInformer.Lock()
	mock.calls.Informer = append(mock.calls.Informer, callInfo)
	lockLdapConfigControllerMockInformer.Unlock()
	return mock.InformerFunc()
}

// InformerCalls gets all the calls that were made to Informer.
// Check the length with:
//     len(mockedLdapConfigController.InformerCalls())
func (mock *LdapConfigControllerMock) InformerCalls() []struct {
} {
	var calls []struct {
	}
	lockLdapConfigControllerMockInformer.RLock()
	calls = mock.calls.Informer
	lockLdapConfigControllerMockInformer.RUnlock()
	return calls
}

// Lister calls ListerFunc.
func (mock *LdapConfigControllerMock) Lister() LdapConfigLister {
	if mock.ListerFunc == nil {
		panic("LdapConfigControllerMock.ListerFunc: method is nil but LdapConfigController.Lister was just called")
	}
	callInfo := struct {
	}{}
	lockLdapConfigControllerMockLister.Lock()
	mock.calls.Lister = append(mock.calls.Lister, callInfo)
	lockLdapConfigControllerMockLister.Unlock()
	return mock.ListerFunc()
}

// ListerCalls gets all the calls that were made to Lister.
// Check the length with:
//     len(mockedLdapConfigController.ListerCalls())
func (mock *LdapConfigControllerMock) ListerCalls() []struct {
} {
	var calls []struct {
	}
	lockLdapConfigControllerMockLister.RLock()
	calls = mock.calls.Lister
	lockLdapConfigControllerMockLister.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *LdapConfigControllerMock) Start(ctx context.Context, threadiness int) error {
	if mock.StartFunc == nil {
		panic("LdapConfigControllerMock.StartFunc: method is nil but LdapConfigController.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Threadiness int
	}{
		Ctx:         ctx,
		Threadiness: threadiness,
	}
	lockLdapConfigControllerMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockLdapConfigControllerMockStart.Unlock()
	return mock.StartFunc(ctx, threadiness)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedLdapConfigController.StartCalls())
func (mock *LdapConfigControllerMock) StartCalls() []struct {
	Ctx         context.Context
	Threadiness int
} {
	var calls []struct {
		Ctx         context.Context
		Threadiness int
	}
	lockLdapConfigControllerMockStart.RLock()
	calls = mock.calls.Start
	lockLdapConfigControllerMockStart.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *LdapConfigControllerMock) Sync(ctx context.Context) error {
	if mock.SyncFunc == nil {
		panic("LdapConfigControllerMock.SyncFunc: method is nil but LdapConfigController.Sync was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockLdapConfigControllerMockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	lockLdapConfigControllerMockSync.Unlock()
	return mock.SyncFunc(ctx)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//     len(mockedLdapConfigController.SyncCalls())
func (mock *LdapConfigControllerMock) SyncCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockLdapConfigControllerMockSync.RLock()
	calls = mock.calls.Sync
	lockLdapConfigControllerMockSync.RUnlock()
	return calls
}

var (
	lockLdapConfigInterfaceMockAddClusterScopedHandler   sync.RWMutex
	lockLdapConfigInterfaceMockAddClusterScopedLifecycle sync.RWMutex
	lockLdapConfigInterfaceMockAddHandler                sync.RWMutex
	lockLdapConfigInterfaceMockAddLifecycle              sync.RWMutex
	lockLdapConfigInterfaceMockController                sync.RWMutex
	lockLdapConfigInterfaceMockCreate                    sync.RWMutex
	lockLdapConfigInterfaceMockDelete                    sync.RWMutex
	lockLdapConfigInterfaceMockDeleteCollection          sync.RWMutex
	lockLdapConfigInterfaceMockDeleteNamespaced          sync.RWMutex
	lockLdapConfigInterfaceMockGet                       sync.RWMutex
	lockLdapConfigInterfaceMockGetNamespaced             sync.RWMutex
	lockLdapConfigInterfaceMockList                      sync.RWMutex
	lockLdapConfigInterfaceMockObjectClient              sync.RWMutex
	lockLdapConfigInterfaceMockUpdate                    sync.RWMutex
	lockLdapConfigInterfaceMockWatch                     sync.RWMutex
)

// Ensure, that LdapConfigInterfaceMock does implement LdapConfigInterface.
// If this is not the case, regenerate this file with moq.
var _ LdapConfigInterface = &LdapConfigInterfaceMock{}

// LdapConfigInterfaceMock is a mock implementation of LdapConfigInterface.
//
//     func TestSomethingThatUsesLdapConfigInterface(t *testing.T) {
//
//         // make and configure a mocked LdapConfigInterface
//         mockedLdapConfigInterface := &LdapConfigInterfaceMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, sync LdapConfigHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddClusterScopedLifecycleFunc: func(ctx context.Context, name string, clusterName string, lifecycle LdapConfigLifecycle)  {
// 	               panic("mock out the AddClusterScopedLifecycle method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, sync LdapConfigHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             AddLifecycleFunc: func(ctx context.Context, name string, lifecycle LdapConfigLifecycle)  {
// 	               panic("mock out the AddLifecycle method")
//             },
//             ControllerFunc: func() LdapConfigController {
// 	               panic("mock out the Controller method")
//             },
//             CreateFunc: func(in1 *LdapConfig) (*LdapConfig, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the Delete method")
//             },
//             DeleteCollectionFunc: func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
// 	               panic("mock out the DeleteCollection method")
//             },
//             DeleteNamespacedFunc: func(namespace string, name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the DeleteNamespaced method")
//             },
//             GetFunc: func(name string, opts v1.GetOptions) (*LdapConfig, error) {
// 	               panic("mock out the Get method")
//             },
//             GetNamespacedFunc: func(namespace string, name string, opts v1.GetOptions) (*LdapConfig, error) {
// 	               panic("mock out the GetNamespaced method")
//             },
//             ListFunc: func(opts v1.ListOptions) (*LdapConfigList, error) {
// 	               panic("mock out the List method")
//             },
//             ObjectClientFunc: func() *objectclient.ObjectClient {
// 	               panic("mock out the ObjectClient method")
//             },
//             UpdateFunc: func(in1 *LdapConfig) (*LdapConfig, error) {
// 	               panic("mock out the Update method")
//             },
//             WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
// 	               panic("mock out the Watch method")
//             },
//         }
//
//         // use mockedLdapConfigInterface in code that requires LdapConfigInterface
//         // and then make assertions.
//
//     }
type LdapConfigInterfaceMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, sync LdapConfigHandlerFunc)

	// AddClusterScopedLifecycleFunc mocks the AddClusterScopedLifecycle method.
	AddClusterScopedLifecycleFunc func(ctx context.Context, name string, clusterName string, lifecycle LdapConfigLifecycle)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, sync LdapConfigHandlerFunc)

	// AddLifecycleFunc mocks the AddLifecycle method.
	AddLifecycleFunc func(ctx context.Context, name string, lifecycle LdapConfigLifecycle)

	// ControllerFunc mocks the Controller method.
	ControllerFunc func() LdapConfigController

	// CreateFunc mocks the Create method.
	CreateFunc func(in1 *LdapConfig) (*LdapConfig, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(name string, options *v1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error

	// DeleteNamespacedFunc mocks the DeleteNamespaced method.
	DeleteNamespacedFunc func(namespace string, name string, options *v1.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(name string, opts v1.GetOptions) (*LdapConfig, error)

	// GetNamespacedFunc mocks the GetNamespaced method.
	GetNamespacedFunc func(namespace string, name string, opts v1.GetOptions) (*LdapConfig, error)

	// ListFunc mocks the List method.
	ListFunc func(opts v1.ListOptions) (*LdapConfigList, error)

	// ObjectClientFunc mocks the ObjectClient method.
	ObjectClientFunc func() *objectclient.ObjectClient

	// UpdateFunc mocks the Update method.
	UpdateFunc func(in1 *LdapConfig) (*LdapConfig, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(opts v1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync LdapConfigHandlerFunc
		}
		// AddClusterScopedLifecycle holds details about calls to the AddClusterScopedLifecycle method.
		AddClusterScopedLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle LdapConfigLifecycle
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync LdapConfigHandlerFunc
		}
		// AddLifecycle holds details about calls to the AddLifecycle method.
		AddLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle LdapConfigLifecycle
		}
		// Controller holds details about calls to the Controller method.
		Controller []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// In1 is the in1 argument value.
			In1 *LdapConfig
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// DeleteOpts is the deleteOpts argument value.
			DeleteOpts *v1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts v1.ListOptions
		}
		// DeleteNamespaced holds details about calls to the DeleteNamespaced method.
		DeleteNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// GetNamespaced holds details about calls to the GetNamespaced method.
		GetNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
		// ObjectClient holds details about calls to the ObjectClient method.
		ObjectClient []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// In1 is the in1 argument value.
			In1 *LdapConfig
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *LdapConfigInterfaceMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, sync LdapConfigHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("LdapConfigInterfaceMock.AddClusterScopedHandlerFunc: method is nil but LdapConfigInterface.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        LdapConfigHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockLdapConfigInterfaceMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockLdapConfigInterfaceMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, sync)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedLdapConfigInterface.AddClusterScopedHandlerCalls())
func (mock *LdapConfigInterfaceMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Sync        LdapConfigHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        LdapConfigHandlerFunc
	}
	lockLdapConfigInterfaceMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockLdapConfigInterfaceMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddClusterScopedLifecycle calls AddClusterScopedLifecycleFunc.
func (mock *LdapConfigInterfaceMock) AddClusterScopedLifecycle(ctx context.Context, name string, clusterName string, lifecycle LdapConfigLifecycle) {
	if mock.AddClusterScopedLifecycleFunc == nil {
		panic("LdapConfigInterfaceMock.AddClusterScopedLifecycleFunc: method is nil but LdapConfigInterface.AddClusterScopedLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   LdapConfigLifecycle
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockLdapConfigInterfaceMockAddClusterScopedLifecycle.Lock()
	mock.calls.AddClusterScopedLifecycle = append(mock.calls.AddClusterScopedLifecycle, callInfo)
	lockLdapConfigInterfaceMockAddClusterScopedLifecycle.Unlock()
	mock.AddClusterScopedLifecycleFunc(ctx, name, clusterName, lifecycle)
}

// AddClusterScopedLifecycleCalls gets all the calls that were made to AddClusterScopedLifecycle.
// Check the length with:
//     len(mockedLdapConfigInterface.AddClusterScopedLifecycleCalls())
func (mock *LdapConfigInterfaceMock) AddClusterScopedLifecycleCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Lifecycle   LdapConfigLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   LdapConfigLifecycle
	}
	lockLdapConfigInterfaceMockAddClusterScopedLifecycle.RLock()
	calls = mock.calls.AddClusterScopedLifecycle
	lockLdapConfigInterfaceMockAddClusterScopedLifecycle.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *LdapConfigInterfaceMock) AddHandler(ctx context.Context, name string, sync LdapConfigHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("LdapConfigInterfaceMock.AddHandlerFunc: method is nil but LdapConfigInterface.AddHandler was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Sync LdapConfigHandlerFunc
	}{
		Ctx:  ctx,
		Name: name,
		Sync: sync,
	}
	lockLdapConfigInterfaceMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockLdapConfigInterfaceMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, sync)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedLdapConfigInterface.AddHandlerCalls())
func (mock *LdapConfigInterfaceMock) AddHandlerCalls() []struct {
	Ctx  context.Context
	Name string
	Sync LdapConfigHandlerFunc
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Sync LdapConfigHandlerFunc
	}
	lockLdapConfigInterfaceMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockLdapConfigInterfaceMockAddHandler.RUnlock()
	return calls
}

// AddLifecycle calls AddLifecycleFunc.
func (mock *LdapConfigInterfaceMock) AddLifecycle(ctx context.Context, name string, lifecycle LdapConfigLifecycle) {
	if mock.AddLifecycleFunc == nil {
		panic("LdapConfigInterfaceMock.AddLifecycleFunc: method is nil but LdapConfigInterface.AddLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Lifecycle LdapConfigLifecycle
	}{
		Ctx:       ctx,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockLdapConfigInterfaceMockAddLifecycle.Lock()
	mock.calls.AddLifecycle = append(mock.calls.AddLifecycle, callInfo)
	lockLdapConfigInterfaceMockAddLifecycle.Unlock()
	mock.AddLifecycleFunc(ctx, name, lifecycle)
}

// AddLifecycleCalls gets all the calls that were made to AddLifecycle.
// Check the length with:
//     len(mockedLdapConfigInterface.AddLifecycleCalls())
func (mock *LdapConfigInterfaceMock) AddLifecycleCalls() []struct {
	Ctx       context.Context
	Name      string
	Lifecycle LdapConfigLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Lifecycle LdapConfigLifecycle
	}
	lockLdapConfigInterfaceMockAddLifecycle.RLock()
	calls = mock.calls.AddLifecycle
	lockLdapConfigInterfaceMockAddLifecycle.RUnlock()
	return calls
}

// Controller calls ControllerFunc.
func (mock *LdapConfigInterfaceMock) Controller() LdapConfigController {
	if mock.ControllerFunc == nil {
		panic("LdapConfigInterfaceMock.ControllerFunc: method is nil but LdapConfigInterface.Controller was just called")
	}
	callInfo := struct {
	}{}
	lockLdapConfigInterfaceMockController.Lock()
	mock.calls.Controller = append(mock.calls.Controller, callInfo)
	lockLdapConfigInterfaceMockController.Unlock()
	return mock.ControllerFunc()
}

// ControllerCalls gets all the calls that were made to Controller.
// Check the length with:
//     len(mockedLdapConfigInterface.ControllerCalls())
func (mock *LdapConfigInterfaceMock) ControllerCalls() []struct {
} {
	var calls []struct {
	}
	lockLdapConfigInterfaceMockController.RLock()
	calls = mock.calls.Controller
	lockLdapConfigInterfaceMockController.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *LdapConfigInterfaceMock) Create(in1 *LdapConfig) (*LdapConfig, error) {
	if mock.CreateFunc == nil {
		panic("LdapConfigInterfaceMock.CreateFunc: method is nil but LdapConfigInterface.Create was just called")
	}
	callInfo := struct {
		In1 *LdapConfig
	}{
		In1: in1,
	}
	lockLdapConfigInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockLdapConfigInterfaceMockCreate.Unlock()
	return mock.CreateFunc(in1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedLdapConfigInterface.CreateCalls())
func (mock *LdapConfigInterfaceMock) CreateCalls() []struct {
	In1 *LdapConfig
} {
	var calls []struct {
		In1 *LdapConfig
	}
	lockLdapConfigInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockLdapConfigInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *LdapConfigInterfaceMock) Delete(name string, options *v1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("LdapConfigInterfaceMock.DeleteFunc: method is nil but LdapConfigInterface.Delete was just called")
	}
	callInfo := struct {
		Name    string
		Options *v1.DeleteOptions
	}{
		Name:    name,
		Options: options,
	}
	lockLdapConfigInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockLdapConfigInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(name, options)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedLdapConfigInterface.DeleteCalls())
func (mock *LdapConfigInterfaceMock) DeleteCalls() []struct {
	Name    string
	Options *v1.DeleteOptions
} {
	var calls []struct {
		Name    string
		Options *v1.DeleteOptions
	}
	lockLdapConfigInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockLdapConfigInterfaceMockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *LdapConfigInterfaceMock) DeleteCollection(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("LdapConfigInterfaceMock.DeleteCollectionFunc: method is nil but LdapConfigInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}{
		DeleteOpts: deleteOpts,
		ListOpts:   listOpts,
	}
	lockLdapConfigInterfaceMockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	lockLdapConfigInterfaceMockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(deleteOpts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedLdapConfigInterface.DeleteCollectionCalls())
func (mock *LdapConfigInterfaceMock) DeleteCollectionCalls() []struct {
	DeleteOpts *v1.DeleteOptions
	ListOpts   v1.ListOptions
} {
	var calls []struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}
	lockLdapConfigInterfaceMockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	lockLdapConfigInterfaceMockDeleteCollection.RUnlock()
	return calls
}

// DeleteNamespaced calls DeleteNamespacedFunc.
func (mock *LdapConfigInterfaceMock) DeleteNamespaced(namespace string, name string, options *v1.DeleteOptions) error {
	if mock.DeleteNamespacedFunc == nil {
		panic("LdapConfigInterfaceMock.DeleteNamespacedFunc: method is nil but LdapConfigInterface.DeleteNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}{
		Namespace: namespace,
		Name:      name,
		Options:   options,
	}
	lockLdapConfigInterfaceMockDeleteNamespaced.Lock()
	mock.calls.DeleteNamespaced = append(mock.calls.DeleteNamespaced, callInfo)
	lockLdapConfigInterfaceMockDeleteNamespaced.Unlock()
	return mock.DeleteNamespacedFunc(namespace, name, options)
}

// DeleteNamespacedCalls gets all the calls that were made to DeleteNamespaced.
// Check the length with:
//     len(mockedLdapConfigInterface.DeleteNamespacedCalls())
func (mock *LdapConfigInterfaceMock) DeleteNamespacedCalls() []struct {
	Namespace string
	Name      string
	Options   *v1.DeleteOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}
	lockLdapConfigInterfaceMockDeleteNamespaced.RLock()
	calls = mock.calls.DeleteNamespaced
	lockLdapConfigInterfaceMockDeleteNamespaced.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *LdapConfigInterfaceMock) Get(name string, opts v1.GetOptions) (*LdapConfig, error) {
	if mock.GetFunc == nil {
		panic("LdapConfigInterfaceMock.GetFunc: method is nil but LdapConfigInterface.Get was just called")
	}
	callInfo := struct {
		Name string
		Opts v1.GetOptions
	}{
		Name: name,
		Opts: opts,
	}
	lockLdapConfigInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockLdapConfigInterfaceMockGet.Unlock()
	return mock.GetFunc(name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedLdapConfigInterface.GetCalls())
func (mock *LdapConfigInterfaceMock) GetCalls() []struct {
	Name string
	Opts v1.GetOptions
} {
	var calls []struct {
		Name string
		Opts v1.GetOptions
	}
	lockLdapConfigInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockLdapConfigInterfaceMockGet.RUnlock()
	return calls
}

// GetNamespaced calls GetNamespacedFunc.
func (mock *LdapConfigInterfaceMock) GetNamespaced(namespace string, name string, opts v1.GetOptions) (*LdapConfig, error) {
	if mock.GetNamespacedFunc == nil {
		panic("LdapConfigInterfaceMock.GetNamespacedFunc: method is nil but LdapConfigInterface.GetNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}{
		Namespace: namespace,
		Name:      name,
		Opts:      opts,
	}
	lockLdapConfigInterfaceMockGetNamespaced.Lock()
	mock.calls.GetNamespaced = append(mock.calls.GetNamespaced, callInfo)
	lockLdapConfigInterfaceMockGetNamespaced.Unlock()
	return mock.GetNamespacedFunc(namespace, name, opts)
}

// GetNamespacedCalls gets all the calls that were made to GetNamespaced.
// Check the length with:
//     len(mockedLdapConfigInterface.GetNamespacedCalls())
func (mock *LdapConfigInterfaceMock) GetNamespacedCalls() []struct {
	Namespace string
	Name      string
	Opts      v1.GetOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}
	lockLdapConfigInterfaceMockGetNamespaced.RLock()
	calls = mock.calls.GetNamespaced
	lockLdapConfigInterfaceMockGetNamespaced.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *LdapConfigInterfaceMock) List(opts v1.ListOptions) (*LdapConfigList, error) {
	if mock.ListFunc == nil {
		panic("LdapConfigInterfaceMock.ListFunc: method is nil but LdapConfigInterface.List was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockLdapConfigInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockLdapConfigInterfaceMockList.Unlock()
	return mock.ListFunc(opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedLdapConfigInterface.ListCalls())
func (mock *LdapConfigInterfaceMock) ListCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockLdapConfigInterfaceMockList.RLock()
	calls = mock.calls.List
	lockLdapConfigInterfaceMockList.RUnlock()
	return calls
}

// ObjectClient calls ObjectClientFunc.
func (mock *LdapConfigInterfaceMock) ObjectClient() *objectclient.ObjectClient {
	if mock.ObjectClientFunc == nil {
		panic("LdapConfigInterfaceMock.ObjectClientFunc: method is nil but LdapConfigInterface.ObjectClient was just called")
	}
	callInfo := struct {
	}{}
	lockLdapConfigInterfaceMockObjectClient.Lock()
	mock.calls.ObjectClient = append(mock.calls.ObjectClient, callInfo)
	lockLdapConfigInterfaceMockObjectClient.Unlock()
	return mock.ObjectClientFunc()
}

// ObjectClientCalls gets all the calls that were made to ObjectClient.
// Check the length with:
//     len(mockedLdapConfigInterface.ObjectClientCalls())
func (mock *LdapConfigInterfaceMock) ObjectClientCalls() []struct {
} {
	var calls []struct {
	}
	lockLdapConfigInterfaceMockObjectClient.RLock()
	calls = mock.calls.ObjectClient
	lockLdapConfigInterfaceMockObjectClient.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *LdapConfigInterfaceMock) Update(in1 *LdapConfig) (*LdapConfig, error) {
	if mock.UpdateFunc == nil {
		panic("LdapConfigInterfaceMock.UpdateFunc: method is nil but LdapConfigInterface.Update was just called")
	}
	callInfo := struct {
		In1 *LdapConfig
	}{
		In1: in1,
	}
	lockLdapConfigInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockLdapConfigInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(in1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedLdapConfigInterface.UpdateCalls())
func (mock *LdapConfigInterfaceMock) UpdateCalls() []struct {
	In1 *LdapConfig
} {
	var calls []struct {
		In1 *LdapConfig
	}
	lockLdapConfigInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockLdapConfigInterfaceMockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *LdapConfigInterfaceMock) Watch(opts v1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("LdapConfigInterfaceMock.WatchFunc: method is nil but LdapConfigInterface.Watch was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockLdapConfigInterfaceMockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	lockLdapConfigInterfaceMockWatch.Unlock()
	return mock.WatchFunc(opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedLdapConfigInterface.WatchCalls())
func (mock *LdapConfigInterfaceMock) WatchCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockLdapConfigInterfaceMockWatch.RLock()
	calls = mock.calls.Watch
	lockLdapConfigInterfaceMockWatch.RUnlock()
	return calls
}
