// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fakes

import (
	context "context"
	sync "sync"

	controller "github.com/rancher/norman/controller"
	objectclient "github.com/rancher/norman/objectclient"
	v1a "github.com/rancher/types/apis/rbac.authorization.k8s.io/v1"
	v1 "k8s.io/api/rbac/v1"
	v1b "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

var (
	lockRoleListerMockGet  sync.RWMutex
	lockRoleListerMockList sync.RWMutex
)

// Ensure, that RoleListerMock does implement RoleLister.
// If this is not the case, regenerate this file with moq.
var _ v1a.RoleLister = &RoleListerMock{}

// RoleListerMock is a mock implementation of RoleLister.
//
//     func TestSomethingThatUsesRoleLister(t *testing.T) {
//
//         // make and configure a mocked RoleLister
//         mockedRoleLister := &RoleListerMock{
//             GetFunc: func(namespace string, name string) (*v1.Role, error) {
// 	               panic("mock out the Get method")
//             },
//             ListFunc: func(namespace string, selector labels.Selector) ([]*v1.Role, error) {
// 	               panic("mock out the List method")
//             },
//         }
//
//         // use mockedRoleLister in code that requires RoleLister
//         // and then make assertions.
//
//     }
type RoleListerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespace string, name string) (*v1.Role, error)

	// ListFunc mocks the List method.
	ListFunc func(namespace string, selector labels.Selector) ([]*v1.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Selector is the selector argument value.
			Selector labels.Selector
		}
	}
}

// Get calls GetFunc.
func (mock *RoleListerMock) Get(namespace string, name string) (*v1.Role, error) {
	if mock.GetFunc == nil {
		panic("RoleListerMock.GetFunc: method is nil but RoleLister.Get was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockRoleListerMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockRoleListerMockGet.Unlock()
	return mock.GetFunc(namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedRoleLister.GetCalls())
func (mock *RoleListerMock) GetCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockRoleListerMockGet.RLock()
	calls = mock.calls.Get
	lockRoleListerMockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *RoleListerMock) List(namespace string, selector labels.Selector) ([]*v1.Role, error) {
	if mock.ListFunc == nil {
		panic("RoleListerMock.ListFunc: method is nil but RoleLister.List was just called")
	}
	callInfo := struct {
		Namespace string
		Selector  labels.Selector
	}{
		Namespace: namespace,
		Selector:  selector,
	}
	lockRoleListerMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockRoleListerMockList.Unlock()
	return mock.ListFunc(namespace, selector)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedRoleLister.ListCalls())
func (mock *RoleListerMock) ListCalls() []struct {
	Namespace string
	Selector  labels.Selector
} {
	var calls []struct {
		Namespace string
		Selector  labels.Selector
	}
	lockRoleListerMockList.RLock()
	calls = mock.calls.List
	lockRoleListerMockList.RUnlock()
	return calls
}

var (
	lockRoleControllerMockAddClusterScopedHandler sync.RWMutex
	lockRoleControllerMockAddHandler              sync.RWMutex
	lockRoleControllerMockEnqueue                 sync.RWMutex
	lockRoleControllerMockGeneric                 sync.RWMutex
	lockRoleControllerMockInformer                sync.RWMutex
	lockRoleControllerMockLister                  sync.RWMutex
	lockRoleControllerMockStart                   sync.RWMutex
	lockRoleControllerMockSync                    sync.RWMutex
)

// Ensure, that RoleControllerMock does implement RoleController.
// If this is not the case, regenerate this file with moq.
var _ v1a.RoleController = &RoleControllerMock{}

// RoleControllerMock is a mock implementation of RoleController.
//
//     func TestSomethingThatUsesRoleController(t *testing.T) {
//
//         // make and configure a mocked RoleController
//         mockedRoleController := &RoleControllerMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, handler v1a.RoleHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, handler v1a.RoleHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             EnqueueFunc: func(namespace string, name string)  {
// 	               panic("mock out the Enqueue method")
//             },
//             GenericFunc: func() controller.GenericController {
// 	               panic("mock out the Generic method")
//             },
//             InformerFunc: func() cache.SharedIndexInformer {
// 	               panic("mock out the Informer method")
//             },
//             ListerFunc: func() v1a.RoleLister {
// 	               panic("mock out the Lister method")
//             },
//             StartFunc: func(ctx context.Context, threadiness int) error {
// 	               panic("mock out the Start method")
//             },
//             SyncFunc: func(ctx context.Context) error {
// 	               panic("mock out the Sync method")
//             },
//         }
//
//         // use mockedRoleController in code that requires RoleController
//         // and then make assertions.
//
//     }
type RoleControllerMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, handler v1a.RoleHandlerFunc)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, handler v1a.RoleHandlerFunc)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(namespace string, name string)

	// GenericFunc mocks the Generic method.
	GenericFunc func() controller.GenericController

	// InformerFunc mocks the Informer method.
	InformerFunc func() cache.SharedIndexInformer

	// ListerFunc mocks the Lister method.
	ListerFunc func() v1a.RoleLister

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, threadiness int) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler v1a.RoleHandlerFunc
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Handler is the handler argument value.
			Handler v1a.RoleHandlerFunc
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Generic holds details about calls to the Generic method.
		Generic []struct {
		}
		// Informer holds details about calls to the Informer method.
		Informer []struct {
		}
		// Lister holds details about calls to the Lister method.
		Lister []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threadiness is the threadiness argument value.
			Threadiness int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *RoleControllerMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, handler v1a.RoleHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("RoleControllerMock.AddClusterScopedHandlerFunc: method is nil but RoleController.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v1a.RoleHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockRoleControllerMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockRoleControllerMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, handler)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedRoleController.AddClusterScopedHandlerCalls())
func (mock *RoleControllerMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Handler     v1a.RoleHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v1a.RoleHandlerFunc
	}
	lockRoleControllerMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockRoleControllerMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *RoleControllerMock) AddHandler(ctx context.Context, name string, handler v1a.RoleHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("RoleControllerMock.AddHandlerFunc: method is nil but RoleController.AddHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Handler v1a.RoleHandlerFunc
	}{
		Ctx:     ctx,
		Name:    name,
		Handler: handler,
	}
	lockRoleControllerMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockRoleControllerMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, handler)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedRoleController.AddHandlerCalls())
func (mock *RoleControllerMock) AddHandlerCalls() []struct {
	Ctx     context.Context
	Name    string
	Handler v1a.RoleHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Handler v1a.RoleHandlerFunc
	}
	lockRoleControllerMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockRoleControllerMockAddHandler.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *RoleControllerMock) Enqueue(namespace string, name string) {
	if mock.EnqueueFunc == nil {
		panic("RoleControllerMock.EnqueueFunc: method is nil but RoleController.Enqueue was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockRoleControllerMockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	lockRoleControllerMockEnqueue.Unlock()
	mock.EnqueueFunc(namespace, name)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//     len(mockedRoleController.EnqueueCalls())
func (mock *RoleControllerMock) EnqueueCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockRoleControllerMockEnqueue.RLock()
	calls = mock.calls.Enqueue
	lockRoleControllerMockEnqueue.RUnlock()
	return calls
}

// Generic calls GenericFunc.
func (mock *RoleControllerMock) Generic() controller.GenericController {
	if mock.GenericFunc == nil {
		panic("RoleControllerMock.GenericFunc: method is nil but RoleController.Generic was just called")
	}
	callInfo := struct {
	}{}
	lockRoleControllerMockGeneric.Lock()
	mock.calls.Generic = append(mock.calls.Generic, callInfo)
	lockRoleControllerMockGeneric.Unlock()
	return mock.GenericFunc()
}

// GenericCalls gets all the calls that were made to Generic.
// Check the length with:
//     len(mockedRoleController.GenericCalls())
func (mock *RoleControllerMock) GenericCalls() []struct {
} {
	var calls []struct {
	}
	lockRoleControllerMockGeneric.RLock()
	calls = mock.calls.Generic
	lockRoleControllerMockGeneric.RUnlock()
	return calls
}

// Informer calls InformerFunc.
func (mock *RoleControllerMock) Informer() cache.SharedIndexInformer {
	if mock.InformerFunc == nil {
		panic("RoleControllerMock.InformerFunc: method is nil but RoleController.Informer was just called")
	}
	callInfo := struct {
	}{}
	lockRoleControllerMockInformer.Lock()
	mock.calls.Informer = append(mock.calls.Informer, callInfo)
	lockRoleControllerMockInformer.Unlock()
	return mock.InformerFunc()
}

// InformerCalls gets all the calls that were made to Informer.
// Check the length with:
//     len(mockedRoleController.InformerCalls())
func (mock *RoleControllerMock) InformerCalls() []struct {
} {
	var calls []struct {
	}
	lockRoleControllerMockInformer.RLock()
	calls = mock.calls.Informer
	lockRoleControllerMockInformer.RUnlock()
	return calls
}

// Lister calls ListerFunc.
func (mock *RoleControllerMock) Lister() v1a.RoleLister {
	if mock.ListerFunc == nil {
		panic("RoleControllerMock.ListerFunc: method is nil but RoleController.Lister was just called")
	}
	callInfo := struct {
	}{}
	lockRoleControllerMockLister.Lock()
	mock.calls.Lister = append(mock.calls.Lister, callInfo)
	lockRoleControllerMockLister.Unlock()
	return mock.ListerFunc()
}

// ListerCalls gets all the calls that were made to Lister.
// Check the length with:
//     len(mockedRoleController.ListerCalls())
func (mock *RoleControllerMock) ListerCalls() []struct {
} {
	var calls []struct {
	}
	lockRoleControllerMockLister.RLock()
	calls = mock.calls.Lister
	lockRoleControllerMockLister.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *RoleControllerMock) Start(ctx context.Context, threadiness int) error {
	if mock.StartFunc == nil {
		panic("RoleControllerMock.StartFunc: method is nil but RoleController.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Threadiness int
	}{
		Ctx:         ctx,
		Threadiness: threadiness,
	}
	lockRoleControllerMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockRoleControllerMockStart.Unlock()
	return mock.StartFunc(ctx, threadiness)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedRoleController.StartCalls())
func (mock *RoleControllerMock) StartCalls() []struct {
	Ctx         context.Context
	Threadiness int
} {
	var calls []struct {
		Ctx         context.Context
		Threadiness int
	}
	lockRoleControllerMockStart.RLock()
	calls = mock.calls.Start
	lockRoleControllerMockStart.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *RoleControllerMock) Sync(ctx context.Context) error {
	if mock.SyncFunc == nil {
		panic("RoleControllerMock.SyncFunc: method is nil but RoleController.Sync was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockRoleControllerMockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	lockRoleControllerMockSync.Unlock()
	return mock.SyncFunc(ctx)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//     len(mockedRoleController.SyncCalls())
func (mock *RoleControllerMock) SyncCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockRoleControllerMockSync.RLock()
	calls = mock.calls.Sync
	lockRoleControllerMockSync.RUnlock()
	return calls
}

var (
	lockRoleInterfaceMockAddClusterScopedHandler   sync.RWMutex
	lockRoleInterfaceMockAddClusterScopedLifecycle sync.RWMutex
	lockRoleInterfaceMockAddHandler                sync.RWMutex
	lockRoleInterfaceMockAddLifecycle              sync.RWMutex
	lockRoleInterfaceMockController                sync.RWMutex
	lockRoleInterfaceMockCreate                    sync.RWMutex
	lockRoleInterfaceMockDelete                    sync.RWMutex
	lockRoleInterfaceMockDeleteCollection          sync.RWMutex
	lockRoleInterfaceMockDeleteNamespaced          sync.RWMutex
	lockRoleInterfaceMockGet                       sync.RWMutex
	lockRoleInterfaceMockGetNamespaced             sync.RWMutex
	lockRoleInterfaceMockList                      sync.RWMutex
	lockRoleInterfaceMockObjectClient              sync.RWMutex
	lockRoleInterfaceMockUpdate                    sync.RWMutex
	lockRoleInterfaceMockWatch                     sync.RWMutex
)

// Ensure, that RoleInterfaceMock does implement RoleInterface.
// If this is not the case, regenerate this file with moq.
var _ v1a.RoleInterface = &RoleInterfaceMock{}

// RoleInterfaceMock is a mock implementation of RoleInterface.
//
//     func TestSomethingThatUsesRoleInterface(t *testing.T) {
//
//         // make and configure a mocked RoleInterface
//         mockedRoleInterface := &RoleInterfaceMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, sync v1a.RoleHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddClusterScopedLifecycleFunc: func(ctx context.Context, name string, clusterName string, lifecycle v1a.RoleLifecycle)  {
// 	               panic("mock out the AddClusterScopedLifecycle method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, sync v1a.RoleHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             AddLifecycleFunc: func(ctx context.Context, name string, lifecycle v1a.RoleLifecycle)  {
// 	               panic("mock out the AddLifecycle method")
//             },
//             ControllerFunc: func() v1a.RoleController {
// 	               panic("mock out the Controller method")
//             },
//             CreateFunc: func(in1 *v1.Role) (*v1.Role, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(name string, options *v1b.DeleteOptions) error {
// 	               panic("mock out the Delete method")
//             },
//             DeleteCollectionFunc: func(deleteOpts *v1b.DeleteOptions, listOpts v1b.ListOptions) error {
// 	               panic("mock out the DeleteCollection method")
//             },
//             DeleteNamespacedFunc: func(namespace string, name string, options *v1b.DeleteOptions) error {
// 	               panic("mock out the DeleteNamespaced method")
//             },
//             GetFunc: func(name string, opts v1b.GetOptions) (*v1.Role, error) {
// 	               panic("mock out the Get method")
//             },
//             GetNamespacedFunc: func(namespace string, name string, opts v1b.GetOptions) (*v1.Role, error) {
// 	               panic("mock out the GetNamespaced method")
//             },
//             ListFunc: func(opts v1b.ListOptions) (*v1a.RoleList, error) {
// 	               panic("mock out the List method")
//             },
//             ObjectClientFunc: func() *objectclient.ObjectClient {
// 	               panic("mock out the ObjectClient method")
//             },
//             UpdateFunc: func(in1 *v1.Role) (*v1.Role, error) {
// 	               panic("mock out the Update method")
//             },
//             WatchFunc: func(opts v1b.ListOptions) (watch.Interface, error) {
// 	               panic("mock out the Watch method")
//             },
//         }
//
//         // use mockedRoleInterface in code that requires RoleInterface
//         // and then make assertions.
//
//     }
type RoleInterfaceMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, sync v1a.RoleHandlerFunc)

	// AddClusterScopedLifecycleFunc mocks the AddClusterScopedLifecycle method.
	AddClusterScopedLifecycleFunc func(ctx context.Context, name string, clusterName string, lifecycle v1a.RoleLifecycle)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, sync v1a.RoleHandlerFunc)

	// AddLifecycleFunc mocks the AddLifecycle method.
	AddLifecycleFunc func(ctx context.Context, name string, lifecycle v1a.RoleLifecycle)

	// ControllerFunc mocks the Controller method.
	ControllerFunc func() v1a.RoleController

	// CreateFunc mocks the Create method.
	CreateFunc func(in1 *v1.Role) (*v1.Role, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(name string, options *v1b.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(deleteOpts *v1b.DeleteOptions, listOpts v1b.ListOptions) error

	// DeleteNamespacedFunc mocks the DeleteNamespaced method.
	DeleteNamespacedFunc func(namespace string, name string, options *v1b.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(name string, opts v1b.GetOptions) (*v1.Role, error)

	// GetNamespacedFunc mocks the GetNamespaced method.
	GetNamespacedFunc func(namespace string, name string, opts v1b.GetOptions) (*v1.Role, error)

	// ListFunc mocks the List method.
	ListFunc func(opts v1b.ListOptions) (*v1a.RoleList, error)

	// ObjectClientFunc mocks the ObjectClient method.
	ObjectClientFunc func() *objectclient.ObjectClient

	// UpdateFunc mocks the Update method.
	UpdateFunc func(in1 *v1.Role) (*v1.Role, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(opts v1b.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync v1a.RoleHandlerFunc
		}
		// AddClusterScopedLifecycle holds details about calls to the AddClusterScopedLifecycle method.
		AddClusterScopedLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v1a.RoleLifecycle
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v1a.RoleHandlerFunc
		}
		// AddLifecycle holds details about calls to the AddLifecycle method.
		AddLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v1a.RoleLifecycle
		}
		// Controller holds details about calls to the Controller method.
		Controller []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// In1 is the in1 argument value.
			In1 *v1.Role
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1b.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// DeleteOpts is the deleteOpts argument value.
			DeleteOpts *v1b.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts v1b.ListOptions
		}
		// DeleteNamespaced holds details about calls to the DeleteNamespaced method.
		DeleteNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1b.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1b.GetOptions
		}
		// GetNamespaced holds details about calls to the GetNamespaced method.
		GetNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1b.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Opts is the opts argument value.
			Opts v1b.ListOptions
		}
		// ObjectClient holds details about calls to the ObjectClient method.
		ObjectClient []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// In1 is the in1 argument value.
			In1 *v1.Role
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Opts is the opts argument value.
			Opts v1b.ListOptions
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *RoleInterfaceMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, sync v1a.RoleHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("RoleInterfaceMock.AddClusterScopedHandlerFunc: method is nil but RoleInterface.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v1a.RoleHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockRoleInterfaceMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockRoleInterfaceMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, sync)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedRoleInterface.AddClusterScopedHandlerCalls())
func (mock *RoleInterfaceMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Sync        v1a.RoleHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v1a.RoleHandlerFunc
	}
	lockRoleInterfaceMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockRoleInterfaceMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddClusterScopedLifecycle calls AddClusterScopedLifecycleFunc.
func (mock *RoleInterfaceMock) AddClusterScopedLifecycle(ctx context.Context, name string, clusterName string, lifecycle v1a.RoleLifecycle) {
	if mock.AddClusterScopedLifecycleFunc == nil {
		panic("RoleInterfaceMock.AddClusterScopedLifecycleFunc: method is nil but RoleInterface.AddClusterScopedLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v1a.RoleLifecycle
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockRoleInterfaceMockAddClusterScopedLifecycle.Lock()
	mock.calls.AddClusterScopedLifecycle = append(mock.calls.AddClusterScopedLifecycle, callInfo)
	lockRoleInterfaceMockAddClusterScopedLifecycle.Unlock()
	mock.AddClusterScopedLifecycleFunc(ctx, name, clusterName, lifecycle)
}

// AddClusterScopedLifecycleCalls gets all the calls that were made to AddClusterScopedLifecycle.
// Check the length with:
//     len(mockedRoleInterface.AddClusterScopedLifecycleCalls())
func (mock *RoleInterfaceMock) AddClusterScopedLifecycleCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Lifecycle   v1a.RoleLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v1a.RoleLifecycle
	}
	lockRoleInterfaceMockAddClusterScopedLifecycle.RLock()
	calls = mock.calls.AddClusterScopedLifecycle
	lockRoleInterfaceMockAddClusterScopedLifecycle.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *RoleInterfaceMock) AddHandler(ctx context.Context, name string, sync v1a.RoleHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("RoleInterfaceMock.AddHandlerFunc: method is nil but RoleInterface.AddHandler was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Sync v1a.RoleHandlerFunc
	}{
		Ctx:  ctx,
		Name: name,
		Sync: sync,
	}
	lockRoleInterfaceMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockRoleInterfaceMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, sync)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedRoleInterface.AddHandlerCalls())
func (mock *RoleInterfaceMock) AddHandlerCalls() []struct {
	Ctx  context.Context
	Name string
	Sync v1a.RoleHandlerFunc
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Sync v1a.RoleHandlerFunc
	}
	lockRoleInterfaceMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockRoleInterfaceMockAddHandler.RUnlock()
	return calls
}

// AddLifecycle calls AddLifecycleFunc.
func (mock *RoleInterfaceMock) AddLifecycle(ctx context.Context, name string, lifecycle v1a.RoleLifecycle) {
	if mock.AddLifecycleFunc == nil {
		panic("RoleInterfaceMock.AddLifecycleFunc: method is nil but RoleInterface.AddLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Lifecycle v1a.RoleLifecycle
	}{
		Ctx:       ctx,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockRoleInterfaceMockAddLifecycle.Lock()
	mock.calls.AddLifecycle = append(mock.calls.AddLifecycle, callInfo)
	lockRoleInterfaceMockAddLifecycle.Unlock()
	mock.AddLifecycleFunc(ctx, name, lifecycle)
}

// AddLifecycleCalls gets all the calls that were made to AddLifecycle.
// Check the length with:
//     len(mockedRoleInterface.AddLifecycleCalls())
func (mock *RoleInterfaceMock) AddLifecycleCalls() []struct {
	Ctx       context.Context
	Name      string
	Lifecycle v1a.RoleLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Lifecycle v1a.RoleLifecycle
	}
	lockRoleInterfaceMockAddLifecycle.RLock()
	calls = mock.calls.AddLifecycle
	lockRoleInterfaceMockAddLifecycle.RUnlock()
	return calls
}

// Controller calls ControllerFunc.
func (mock *RoleInterfaceMock) Controller() v1a.RoleController {
	if mock.ControllerFunc == nil {
		panic("RoleInterfaceMock.ControllerFunc: method is nil but RoleInterface.Controller was just called")
	}
	callInfo := struct {
	}{}
	lockRoleInterfaceMockController.Lock()
	mock.calls.Controller = append(mock.calls.Controller, callInfo)
	lockRoleInterfaceMockController.Unlock()
	return mock.ControllerFunc()
}

// ControllerCalls gets all the calls that were made to Controller.
// Check the length with:
//     len(mockedRoleInterface.ControllerCalls())
func (mock *RoleInterfaceMock) ControllerCalls() []struct {
} {
	var calls []struct {
	}
	lockRoleInterfaceMockController.RLock()
	calls = mock.calls.Controller
	lockRoleInterfaceMockController.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *RoleInterfaceMock) Create(in1 *v1.Role) (*v1.Role, error) {
	if mock.CreateFunc == nil {
		panic("RoleInterfaceMock.CreateFunc: method is nil but RoleInterface.Create was just called")
	}
	callInfo := struct {
		In1 *v1.Role
	}{
		In1: in1,
	}
	lockRoleInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockRoleInterfaceMockCreate.Unlock()
	return mock.CreateFunc(in1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedRoleInterface.CreateCalls())
func (mock *RoleInterfaceMock) CreateCalls() []struct {
	In1 *v1.Role
} {
	var calls []struct {
		In1 *v1.Role
	}
	lockRoleInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockRoleInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RoleInterfaceMock) Delete(name string, options *v1b.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("RoleInterfaceMock.DeleteFunc: method is nil but RoleInterface.Delete was just called")
	}
	callInfo := struct {
		Name    string
		Options *v1b.DeleteOptions
	}{
		Name:    name,
		Options: options,
	}
	lockRoleInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockRoleInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(name, options)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedRoleInterface.DeleteCalls())
func (mock *RoleInterfaceMock) DeleteCalls() []struct {
	Name    string
	Options *v1b.DeleteOptions
} {
	var calls []struct {
		Name    string
		Options *v1b.DeleteOptions
	}
	lockRoleInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockRoleInterfaceMockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *RoleInterfaceMock) DeleteCollection(deleteOpts *v1b.DeleteOptions, listOpts v1b.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("RoleInterfaceMock.DeleteCollectionFunc: method is nil but RoleInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		DeleteOpts *v1b.DeleteOptions
		ListOpts   v1b.ListOptions
	}{
		DeleteOpts: deleteOpts,
		ListOpts:   listOpts,
	}
	lockRoleInterfaceMockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	lockRoleInterfaceMockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(deleteOpts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedRoleInterface.DeleteCollectionCalls())
func (mock *RoleInterfaceMock) DeleteCollectionCalls() []struct {
	DeleteOpts *v1b.DeleteOptions
	ListOpts   v1b.ListOptions
} {
	var calls []struct {
		DeleteOpts *v1b.DeleteOptions
		ListOpts   v1b.ListOptions
	}
	lockRoleInterfaceMockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	lockRoleInterfaceMockDeleteCollection.RUnlock()
	return calls
}

// DeleteNamespaced calls DeleteNamespacedFunc.
func (mock *RoleInterfaceMock) DeleteNamespaced(namespace string, name string, options *v1b.DeleteOptions) error {
	if mock.DeleteNamespacedFunc == nil {
		panic("RoleInterfaceMock.DeleteNamespacedFunc: method is nil but RoleInterface.DeleteNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Options   *v1b.DeleteOptions
	}{
		Namespace: namespace,
		Name:      name,
		Options:   options,
	}
	lockRoleInterfaceMockDeleteNamespaced.Lock()
	mock.calls.DeleteNamespaced = append(mock.calls.DeleteNamespaced, callInfo)
	lockRoleInterfaceMockDeleteNamespaced.Unlock()
	return mock.DeleteNamespacedFunc(namespace, name, options)
}

// DeleteNamespacedCalls gets all the calls that were made to DeleteNamespaced.
// Check the length with:
//     len(mockedRoleInterface.DeleteNamespacedCalls())
func (mock *RoleInterfaceMock) DeleteNamespacedCalls() []struct {
	Namespace string
	Name      string
	Options   *v1b.DeleteOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Options   *v1b.DeleteOptions
	}
	lockRoleInterfaceMockDeleteNamespaced.RLock()
	calls = mock.calls.DeleteNamespaced
	lockRoleInterfaceMockDeleteNamespaced.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RoleInterfaceMock) Get(name string, opts v1b.GetOptions) (*v1.Role, error) {
	if mock.GetFunc == nil {
		panic("RoleInterfaceMock.GetFunc: method is nil but RoleInterface.Get was just called")
	}
	callInfo := struct {
		Name string
		Opts v1b.GetOptions
	}{
		Name: name,
		Opts: opts,
	}
	lockRoleInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockRoleInterfaceMockGet.Unlock()
	return mock.GetFunc(name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedRoleInterface.GetCalls())
func (mock *RoleInterfaceMock) GetCalls() []struct {
	Name string
	Opts v1b.GetOptions
} {
	var calls []struct {
		Name string
		Opts v1b.GetOptions
	}
	lockRoleInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockRoleInterfaceMockGet.RUnlock()
	return calls
}

// GetNamespaced calls GetNamespacedFunc.
func (mock *RoleInterfaceMock) GetNamespaced(namespace string, name string, opts v1b.GetOptions) (*v1.Role, error) {
	if mock.GetNamespacedFunc == nil {
		panic("RoleInterfaceMock.GetNamespacedFunc: method is nil but RoleInterface.GetNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Opts      v1b.GetOptions
	}{
		Namespace: namespace,
		Name:      name,
		Opts:      opts,
	}
	lockRoleInterfaceMockGetNamespaced.Lock()
	mock.calls.GetNamespaced = append(mock.calls.GetNamespaced, callInfo)
	lockRoleInterfaceMockGetNamespaced.Unlock()
	return mock.GetNamespacedFunc(namespace, name, opts)
}

// GetNamespacedCalls gets all the calls that were made to GetNamespaced.
// Check the length with:
//     len(mockedRoleInterface.GetNamespacedCalls())
func (mock *RoleInterfaceMock) GetNamespacedCalls() []struct {
	Namespace string
	Name      string
	Opts      v1b.GetOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Opts      v1b.GetOptions
	}
	lockRoleInterfaceMockGetNamespaced.RLock()
	calls = mock.calls.GetNamespaced
	lockRoleInterfaceMockGetNamespaced.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *RoleInterfaceMock) List(opts v1b.ListOptions) (*v1a.RoleList, error) {
	if mock.ListFunc == nil {
		panic("RoleInterfaceMock.ListFunc: method is nil but RoleInterface.List was just called")
	}
	callInfo := struct {
		Opts v1b.ListOptions
	}{
		Opts: opts,
	}
	lockRoleInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockRoleInterfaceMockList.Unlock()
	return mock.ListFunc(opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedRoleInterface.ListCalls())
func (mock *RoleInterfaceMock) ListCalls() []struct {
	Opts v1b.ListOptions
} {
	var calls []struct {
		Opts v1b.ListOptions
	}
	lockRoleInterfaceMockList.RLock()
	calls = mock.calls.List
	lockRoleInterfaceMockList.RUnlock()
	return calls
}

// ObjectClient calls ObjectClientFunc.
func (mock *RoleInterfaceMock) ObjectClient() *objectclient.ObjectClient {
	if mock.ObjectClientFunc == nil {
		panic("RoleInterfaceMock.ObjectClientFunc: method is nil but RoleInterface.ObjectClient was just called")
	}
	callInfo := struct {
	}{}
	lockRoleInterfaceMockObjectClient.Lock()
	mock.calls.ObjectClient = append(mock.calls.ObjectClient, callInfo)
	lockRoleInterfaceMockObjectClient.Unlock()
	return mock.ObjectClientFunc()
}

// ObjectClientCalls gets all the calls that were made to ObjectClient.
// Check the length with:
//     len(mockedRoleInterface.ObjectClientCalls())
func (mock *RoleInterfaceMock) ObjectClientCalls() []struct {
} {
	var calls []struct {
	}
	lockRoleInterfaceMockObjectClient.RLock()
	calls = mock.calls.ObjectClient
	lockRoleInterfaceMockObjectClient.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RoleInterfaceMock) Update(in1 *v1.Role) (*v1.Role, error) {
	if mock.UpdateFunc == nil {
		panic("RoleInterfaceMock.UpdateFunc: method is nil but RoleInterface.Update was just called")
	}
	callInfo := struct {
		In1 *v1.Role
	}{
		In1: in1,
	}
	lockRoleInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockRoleInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(in1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedRoleInterface.UpdateCalls())
func (mock *RoleInterfaceMock) UpdateCalls() []struct {
	In1 *v1.Role
} {
	var calls []struct {
		In1 *v1.Role
	}
	lockRoleInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockRoleInterfaceMockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *RoleInterfaceMock) Watch(opts v1b.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("RoleInterfaceMock.WatchFunc: method is nil but RoleInterface.Watch was just called")
	}
	callInfo := struct {
		Opts v1b.ListOptions
	}{
		Opts: opts,
	}
	lockRoleInterfaceMockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	lockRoleInterfaceMockWatch.Unlock()
	return mock.WatchFunc(opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedRoleInterface.WatchCalls())
func (mock *RoleInterfaceMock) WatchCalls() []struct {
	Opts v1b.ListOptions
} {
	var calls []struct {
		Opts v1b.ListOptions
	}
	lockRoleInterfaceMockWatch.RLock()
	calls = mock.calls.Watch
	lockRoleInterfaceMockWatch.RUnlock()
	return calls
}

var (
	lockRolesGetterMockRoles sync.RWMutex
)

// Ensure, that RolesGetterMock does implement RolesGetter.
// If this is not the case, regenerate this file with moq.
var _ v1a.RolesGetter = &RolesGetterMock{}

// RolesGetterMock is a mock implementation of RolesGetter.
//
//     func TestSomethingThatUsesRolesGetter(t *testing.T) {
//
//         // make and configure a mocked RolesGetter
//         mockedRolesGetter := &RolesGetterMock{
//             RolesFunc: func(namespace string) v1a.RoleInterface {
// 	               panic("mock out the Roles method")
//             },
//         }
//
//         // use mockedRolesGetter in code that requires RolesGetter
//         // and then make assertions.
//
//     }
type RolesGetterMock struct {
	// RolesFunc mocks the Roles method.
	RolesFunc func(namespace string) v1a.RoleInterface

	// calls tracks calls to the methods.
	calls struct {
		// Roles holds details about calls to the Roles method.
		Roles []struct {
			// Namespace is the namespace argument value.
			Namespace string
		}
	}
}

// Roles calls RolesFunc.
func (mock *RolesGetterMock) Roles(namespace string) v1a.RoleInterface {
	if mock.RolesFunc == nil {
		panic("RolesGetterMock.RolesFunc: method is nil but RolesGetter.Roles was just called")
	}
	callInfo := struct {
		Namespace string
	}{
		Namespace: namespace,
	}
	lockRolesGetterMockRoles.Lock()
	mock.calls.Roles = append(mock.calls.Roles, callInfo)
	lockRolesGetterMockRoles.Unlock()
	return mock.RolesFunc(namespace)
}

// RolesCalls gets all the calls that were made to Roles.
// Check the length with:
//     len(mockedRolesGetter.RolesCalls())
func (mock *RolesGetterMock) RolesCalls() []struct {
	Namespace string
} {
	var calls []struct {
		Namespace string
	}
	lockRolesGetterMockRoles.RLock()
	calls = mock.calls.Roles
	lockRolesGetterMockRoles.RUnlock()
	return calls
}
