// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package v1

import (
	"context"
	"sync"

	"github.com/rancher/norman/controller"
	"github.com/rancher/norman/objectclient"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
)

var (
	lockEventListerMockGet  sync.RWMutex
	lockEventListerMockList sync.RWMutex
)

// Ensure, that EventListerMock does implement EventLister.
// If this is not the case, regenerate this file with moq.
var _ EventLister = &EventListerMock{}

// EventListerMock is a mock implementation of EventLister.
//
//     func TestSomethingThatUsesEventLister(t *testing.T) {
//
//         // make and configure a mocked EventLister
//         mockedEventLister := &EventListerMock{
//             GetFunc: func(namespace string, name string) (*v1.Event, error) {
// 	               panic("mock out the Get method")
//             },
//             ListFunc: func(namespace string, selector labels.Selector) ([]*v1.Event, error) {
// 	               panic("mock out the List method")
//             },
//         }
//
//         // use mockedEventLister in code that requires EventLister
//         // and then make assertions.
//
//     }
type EventListerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespace string, name string) (*v1.Event, error)

	// ListFunc mocks the List method.
	ListFunc func(namespace string, selector labels.Selector) ([]*v1.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Selector is the selector argument value.
			Selector labels.Selector
		}
	}
}

// Get calls GetFunc.
func (mock *EventListerMock) Get(namespace string, name string) (*v1.Event, error) {
	if mock.GetFunc == nil {
		panic("EventListerMock.GetFunc: method is nil but EventLister.Get was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockEventListerMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockEventListerMockGet.Unlock()
	return mock.GetFunc(namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedEventLister.GetCalls())
func (mock *EventListerMock) GetCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockEventListerMockGet.RLock()
	calls = mock.calls.Get
	lockEventListerMockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *EventListerMock) List(namespace string, selector labels.Selector) ([]*v1.Event, error) {
	if mock.ListFunc == nil {
		panic("EventListerMock.ListFunc: method is nil but EventLister.List was just called")
	}
	callInfo := struct {
		Namespace string
		Selector  labels.Selector
	}{
		Namespace: namespace,
		Selector:  selector,
	}
	lockEventListerMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockEventListerMockList.Unlock()
	return mock.ListFunc(namespace, selector)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedEventLister.ListCalls())
func (mock *EventListerMock) ListCalls() []struct {
	Namespace string
	Selector  labels.Selector
} {
	var calls []struct {
		Namespace string
		Selector  labels.Selector
	}
	lockEventListerMockList.RLock()
	calls = mock.calls.List
	lockEventListerMockList.RUnlock()
	return calls
}

var (
	lockEventControllerMockAddClusterScopedHandler sync.RWMutex
	lockEventControllerMockAddHandler              sync.RWMutex
	lockEventControllerMockEnqueue                 sync.RWMutex
	lockEventControllerMockGeneric                 sync.RWMutex
	lockEventControllerMockInformer                sync.RWMutex
	lockEventControllerMockLister                  sync.RWMutex
	lockEventControllerMockStart                   sync.RWMutex
	lockEventControllerMockSync                    sync.RWMutex
)

// Ensure, that EventControllerMock does implement EventController.
// If this is not the case, regenerate this file with moq.
var _ EventController = &EventControllerMock{}

// EventControllerMock is a mock implementation of EventController.
//
//     func TestSomethingThatUsesEventController(t *testing.T) {
//
//         // make and configure a mocked EventController
//         mockedEventController := &EventControllerMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, handler EventHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, handler EventHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             EnqueueFunc: func(namespace string, name string)  {
// 	               panic("mock out the Enqueue method")
//             },
//             GenericFunc: func() controller.GenericController {
// 	               panic("mock out the Generic method")
//             },
//             InformerFunc: func() cache.SharedIndexInformer {
// 	               panic("mock out the Informer method")
//             },
//             ListerFunc: func() EventLister {
// 	               panic("mock out the Lister method")
//             },
//             StartFunc: func(ctx context.Context, threadiness int) error {
// 	               panic("mock out the Start method")
//             },
//             SyncFunc: func(ctx context.Context) error {
// 	               panic("mock out the Sync method")
//             },
//         }
//
//         // use mockedEventController in code that requires EventController
//         // and then make assertions.
//
//     }
type EventControllerMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, handler EventHandlerFunc)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, handler EventHandlerFunc)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(namespace string, name string)

	// GenericFunc mocks the Generic method.
	GenericFunc func() controller.GenericController

	// InformerFunc mocks the Informer method.
	InformerFunc func() cache.SharedIndexInformer

	// ListerFunc mocks the Lister method.
	ListerFunc func() EventLister

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, threadiness int) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler EventHandlerFunc
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Handler is the handler argument value.
			Handler EventHandlerFunc
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Generic holds details about calls to the Generic method.
		Generic []struct {
		}
		// Informer holds details about calls to the Informer method.
		Informer []struct {
		}
		// Lister holds details about calls to the Lister method.
		Lister []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threadiness is the threadiness argument value.
			Threadiness int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *EventControllerMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, handler EventHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("EventControllerMock.AddClusterScopedHandlerFunc: method is nil but EventController.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     EventHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockEventControllerMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockEventControllerMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, handler)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedEventController.AddClusterScopedHandlerCalls())
func (mock *EventControllerMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Handler     EventHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     EventHandlerFunc
	}
	lockEventControllerMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockEventControllerMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *EventControllerMock) AddHandler(ctx context.Context, name string, handler EventHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("EventControllerMock.AddHandlerFunc: method is nil but EventController.AddHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Handler EventHandlerFunc
	}{
		Ctx:     ctx,
		Name:    name,
		Handler: handler,
	}
	lockEventControllerMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockEventControllerMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, handler)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedEventController.AddHandlerCalls())
func (mock *EventControllerMock) AddHandlerCalls() []struct {
	Ctx     context.Context
	Name    string
	Handler EventHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Handler EventHandlerFunc
	}
	lockEventControllerMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockEventControllerMockAddHandler.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *EventControllerMock) Enqueue(namespace string, name string) {
	if mock.EnqueueFunc == nil {
		panic("EventControllerMock.EnqueueFunc: method is nil but EventController.Enqueue was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockEventControllerMockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	lockEventControllerMockEnqueue.Unlock()
	mock.EnqueueFunc(namespace, name)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//     len(mockedEventController.EnqueueCalls())
func (mock *EventControllerMock) EnqueueCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockEventControllerMockEnqueue.RLock()
	calls = mock.calls.Enqueue
	lockEventControllerMockEnqueue.RUnlock()
	return calls
}

// Generic calls GenericFunc.
func (mock *EventControllerMock) Generic() controller.GenericController {
	if mock.GenericFunc == nil {
		panic("EventControllerMock.GenericFunc: method is nil but EventController.Generic was just called")
	}
	callInfo := struct {
	}{}
	lockEventControllerMockGeneric.Lock()
	mock.calls.Generic = append(mock.calls.Generic, callInfo)
	lockEventControllerMockGeneric.Unlock()
	return mock.GenericFunc()
}

// GenericCalls gets all the calls that were made to Generic.
// Check the length with:
//     len(mockedEventController.GenericCalls())
func (mock *EventControllerMock) GenericCalls() []struct {
} {
	var calls []struct {
	}
	lockEventControllerMockGeneric.RLock()
	calls = mock.calls.Generic
	lockEventControllerMockGeneric.RUnlock()
	return calls
}

// Informer calls InformerFunc.
func (mock *EventControllerMock) Informer() cache.SharedIndexInformer {
	if mock.InformerFunc == nil {
		panic("EventControllerMock.InformerFunc: method is nil but EventController.Informer was just called")
	}
	callInfo := struct {
	}{}
	lockEventControllerMockInformer.Lock()
	mock.calls.Informer = append(mock.calls.Informer, callInfo)
	lockEventControllerMockInformer.Unlock()
	return mock.InformerFunc()
}

// InformerCalls gets all the calls that were made to Informer.
// Check the length with:
//     len(mockedEventController.InformerCalls())
func (mock *EventControllerMock) InformerCalls() []struct {
} {
	var calls []struct {
	}
	lockEventControllerMockInformer.RLock()
	calls = mock.calls.Informer
	lockEventControllerMockInformer.RUnlock()
	return calls
}

// Lister calls ListerFunc.
func (mock *EventControllerMock) Lister() EventLister {
	if mock.ListerFunc == nil {
		panic("EventControllerMock.ListerFunc: method is nil but EventController.Lister was just called")
	}
	callInfo := struct {
	}{}
	lockEventControllerMockLister.Lock()
	mock.calls.Lister = append(mock.calls.Lister, callInfo)
	lockEventControllerMockLister.Unlock()
	return mock.ListerFunc()
}

// ListerCalls gets all the calls that were made to Lister.
// Check the length with:
//     len(mockedEventController.ListerCalls())
func (mock *EventControllerMock) ListerCalls() []struct {
} {
	var calls []struct {
	}
	lockEventControllerMockLister.RLock()
	calls = mock.calls.Lister
	lockEventControllerMockLister.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *EventControllerMock) Start(ctx context.Context, threadiness int) error {
	if mock.StartFunc == nil {
		panic("EventControllerMock.StartFunc: method is nil but EventController.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Threadiness int
	}{
		Ctx:         ctx,
		Threadiness: threadiness,
	}
	lockEventControllerMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockEventControllerMockStart.Unlock()
	return mock.StartFunc(ctx, threadiness)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedEventController.StartCalls())
func (mock *EventControllerMock) StartCalls() []struct {
	Ctx         context.Context
	Threadiness int
} {
	var calls []struct {
		Ctx         context.Context
		Threadiness int
	}
	lockEventControllerMockStart.RLock()
	calls = mock.calls.Start
	lockEventControllerMockStart.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *EventControllerMock) Sync(ctx context.Context) error {
	if mock.SyncFunc == nil {
		panic("EventControllerMock.SyncFunc: method is nil but EventController.Sync was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockEventControllerMockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	lockEventControllerMockSync.Unlock()
	return mock.SyncFunc(ctx)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//     len(mockedEventController.SyncCalls())
func (mock *EventControllerMock) SyncCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockEventControllerMockSync.RLock()
	calls = mock.calls.Sync
	lockEventControllerMockSync.RUnlock()
	return calls
}

var (
	lockEventInterfaceMockAddClusterScopedHandler   sync.RWMutex
	lockEventInterfaceMockAddClusterScopedLifecycle sync.RWMutex
	lockEventInterfaceMockAddHandler                sync.RWMutex
	lockEventInterfaceMockAddLifecycle              sync.RWMutex
	lockEventInterfaceMockController                sync.RWMutex
	lockEventInterfaceMockCreate                    sync.RWMutex
	lockEventInterfaceMockDelete                    sync.RWMutex
	lockEventInterfaceMockDeleteCollection          sync.RWMutex
	lockEventInterfaceMockDeleteNamespaced          sync.RWMutex
	lockEventInterfaceMockGet                       sync.RWMutex
	lockEventInterfaceMockGetNamespaced             sync.RWMutex
	lockEventInterfaceMockList                      sync.RWMutex
	lockEventInterfaceMockObjectClient              sync.RWMutex
	lockEventInterfaceMockUpdate                    sync.RWMutex
	lockEventInterfaceMockWatch                     sync.RWMutex
)

// Ensure, that EventInterfaceMock does implement EventInterface.
// If this is not the case, regenerate this file with moq.
var _ EventInterface = &EventInterfaceMock{}

// EventInterfaceMock is a mock implementation of EventInterface.
//
//     func TestSomethingThatUsesEventInterface(t *testing.T) {
//
//         // make and configure a mocked EventInterface
//         mockedEventInterface := &EventInterfaceMock{
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, sync EventHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddClusterScopedLifecycleFunc: func(ctx context.Context, name string, clusterName string, lifecycle EventLifecycle)  {
// 	               panic("mock out the AddClusterScopedLifecycle method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, sync EventHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             AddLifecycleFunc: func(ctx context.Context, name string, lifecycle EventLifecycle)  {
// 	               panic("mock out the AddLifecycle method")
//             },
//             ControllerFunc: func() EventController {
// 	               panic("mock out the Controller method")
//             },
//             CreateFunc: func(in1 *v1.Event) (*v1.Event, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the Delete method")
//             },
//             DeleteCollectionFunc: func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
// 	               panic("mock out the DeleteCollection method")
//             },
//             DeleteNamespacedFunc: func(namespace string, name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the DeleteNamespaced method")
//             },
//             GetFunc: func(name string, opts v1.GetOptions) (*v1.Event, error) {
// 	               panic("mock out the Get method")
//             },
//             GetNamespacedFunc: func(namespace string, name string, opts v1.GetOptions) (*v1.Event, error) {
// 	               panic("mock out the GetNamespaced method")
//             },
//             ListFunc: func(opts v1.ListOptions) (*EventList, error) {
// 	               panic("mock out the List method")
//             },
//             ObjectClientFunc: func() *objectclient.ObjectClient {
// 	               panic("mock out the ObjectClient method")
//             },
//             UpdateFunc: func(in1 *v1.Event) (*v1.Event, error) {
// 	               panic("mock out the Update method")
//             },
//             WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
// 	               panic("mock out the Watch method")
//             },
//         }
//
//         // use mockedEventInterface in code that requires EventInterface
//         // and then make assertions.
//
//     }
type EventInterfaceMock struct {
	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, sync EventHandlerFunc)

	// AddClusterScopedLifecycleFunc mocks the AddClusterScopedLifecycle method.
	AddClusterScopedLifecycleFunc func(ctx context.Context, name string, clusterName string, lifecycle EventLifecycle)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, sync EventHandlerFunc)

	// AddLifecycleFunc mocks the AddLifecycle method.
	AddLifecycleFunc func(ctx context.Context, name string, lifecycle EventLifecycle)

	// ControllerFunc mocks the Controller method.
	ControllerFunc func() EventController

	// CreateFunc mocks the Create method.
	CreateFunc func(in1 *v1.Event) (*v1.Event, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(name string, options *v1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error

	// DeleteNamespacedFunc mocks the DeleteNamespaced method.
	DeleteNamespacedFunc func(namespace string, name string, options *v1.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(name string, opts v1.GetOptions) (*v1.Event, error)

	// GetNamespacedFunc mocks the GetNamespaced method.
	GetNamespacedFunc func(namespace string, name string, opts v1.GetOptions) (*v1.Event, error)

	// ListFunc mocks the List method.
	ListFunc func(opts v1.ListOptions) (*EventList, error)

	// ObjectClientFunc mocks the ObjectClient method.
	ObjectClientFunc func() *objectclient.ObjectClient

	// UpdateFunc mocks the Update method.
	UpdateFunc func(in1 *v1.Event) (*v1.Event, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(opts v1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync EventHandlerFunc
		}
		// AddClusterScopedLifecycle holds details about calls to the AddClusterScopedLifecycle method.
		AddClusterScopedLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle EventLifecycle
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync EventHandlerFunc
		}
		// AddLifecycle holds details about calls to the AddLifecycle method.
		AddLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle EventLifecycle
		}
		// Controller holds details about calls to the Controller method.
		Controller []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// In1 is the in1 argument value.
			In1 *v1.Event
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// DeleteOpts is the deleteOpts argument value.
			DeleteOpts *v1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts v1.ListOptions
		}
		// DeleteNamespaced holds details about calls to the DeleteNamespaced method.
		DeleteNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// GetNamespaced holds details about calls to the GetNamespaced method.
		GetNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
		// ObjectClient holds details about calls to the ObjectClient method.
		ObjectClient []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// In1 is the in1 argument value.
			In1 *v1.Event
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
	}
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *EventInterfaceMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, sync EventHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("EventInterfaceMock.AddClusterScopedHandlerFunc: method is nil but EventInterface.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        EventHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockEventInterfaceMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockEventInterfaceMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, sync)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedEventInterface.AddClusterScopedHandlerCalls())
func (mock *EventInterfaceMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Sync        EventHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        EventHandlerFunc
	}
	lockEventInterfaceMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockEventInterfaceMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddClusterScopedLifecycle calls AddClusterScopedLifecycleFunc.
func (mock *EventInterfaceMock) AddClusterScopedLifecycle(ctx context.Context, name string, clusterName string, lifecycle EventLifecycle) {
	if mock.AddClusterScopedLifecycleFunc == nil {
		panic("EventInterfaceMock.AddClusterScopedLifecycleFunc: method is nil but EventInterface.AddClusterScopedLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   EventLifecycle
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockEventInterfaceMockAddClusterScopedLifecycle.Lock()
	mock.calls.AddClusterScopedLifecycle = append(mock.calls.AddClusterScopedLifecycle, callInfo)
	lockEventInterfaceMockAddClusterScopedLifecycle.Unlock()
	mock.AddClusterScopedLifecycleFunc(ctx, name, clusterName, lifecycle)
}

// AddClusterScopedLifecycleCalls gets all the calls that were made to AddClusterScopedLifecycle.
// Check the length with:
//     len(mockedEventInterface.AddClusterScopedLifecycleCalls())
func (mock *EventInterfaceMock) AddClusterScopedLifecycleCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Lifecycle   EventLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   EventLifecycle
	}
	lockEventInterfaceMockAddClusterScopedLifecycle.RLock()
	calls = mock.calls.AddClusterScopedLifecycle
	lockEventInterfaceMockAddClusterScopedLifecycle.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *EventInterfaceMock) AddHandler(ctx context.Context, name string, sync EventHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("EventInterfaceMock.AddHandlerFunc: method is nil but EventInterface.AddHandler was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Sync EventHandlerFunc
	}{
		Ctx:  ctx,
		Name: name,
		Sync: sync,
	}
	lockEventInterfaceMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockEventInterfaceMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, sync)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedEventInterface.AddHandlerCalls())
func (mock *EventInterfaceMock) AddHandlerCalls() []struct {
	Ctx  context.Context
	Name string
	Sync EventHandlerFunc
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Sync EventHandlerFunc
	}
	lockEventInterfaceMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockEventInterfaceMockAddHandler.RUnlock()
	return calls
}

// AddLifecycle calls AddLifecycleFunc.
func (mock *EventInterfaceMock) AddLifecycle(ctx context.Context, name string, lifecycle EventLifecycle) {
	if mock.AddLifecycleFunc == nil {
		panic("EventInterfaceMock.AddLifecycleFunc: method is nil but EventInterface.AddLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Lifecycle EventLifecycle
	}{
		Ctx:       ctx,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockEventInterfaceMockAddLifecycle.Lock()
	mock.calls.AddLifecycle = append(mock.calls.AddLifecycle, callInfo)
	lockEventInterfaceMockAddLifecycle.Unlock()
	mock.AddLifecycleFunc(ctx, name, lifecycle)
}

// AddLifecycleCalls gets all the calls that were made to AddLifecycle.
// Check the length with:
//     len(mockedEventInterface.AddLifecycleCalls())
func (mock *EventInterfaceMock) AddLifecycleCalls() []struct {
	Ctx       context.Context
	Name      string
	Lifecycle EventLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Lifecycle EventLifecycle
	}
	lockEventInterfaceMockAddLifecycle.RLock()
	calls = mock.calls.AddLifecycle
	lockEventInterfaceMockAddLifecycle.RUnlock()
	return calls
}

// Controller calls ControllerFunc.
func (mock *EventInterfaceMock) Controller() EventController {
	if mock.ControllerFunc == nil {
		panic("EventInterfaceMock.ControllerFunc: method is nil but EventInterface.Controller was just called")
	}
	callInfo := struct {
	}{}
	lockEventInterfaceMockController.Lock()
	mock.calls.Controller = append(mock.calls.Controller, callInfo)
	lockEventInterfaceMockController.Unlock()
	return mock.ControllerFunc()
}

// ControllerCalls gets all the calls that were made to Controller.
// Check the length with:
//     len(mockedEventInterface.ControllerCalls())
func (mock *EventInterfaceMock) ControllerCalls() []struct {
} {
	var calls []struct {
	}
	lockEventInterfaceMockController.RLock()
	calls = mock.calls.Controller
	lockEventInterfaceMockController.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *EventInterfaceMock) Create(in1 *v1.Event) (*v1.Event, error) {
	if mock.CreateFunc == nil {
		panic("EventInterfaceMock.CreateFunc: method is nil but EventInterface.Create was just called")
	}
	callInfo := struct {
		In1 *v1.Event
	}{
		In1: in1,
	}
	lockEventInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockEventInterfaceMockCreate.Unlock()
	return mock.CreateFunc(in1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedEventInterface.CreateCalls())
func (mock *EventInterfaceMock) CreateCalls() []struct {
	In1 *v1.Event
} {
	var calls []struct {
		In1 *v1.Event
	}
	lockEventInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockEventInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *EventInterfaceMock) Delete(name string, options *v1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("EventInterfaceMock.DeleteFunc: method is nil but EventInterface.Delete was just called")
	}
	callInfo := struct {
		Name    string
		Options *v1.DeleteOptions
	}{
		Name:    name,
		Options: options,
	}
	lockEventInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockEventInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(name, options)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedEventInterface.DeleteCalls())
func (mock *EventInterfaceMock) DeleteCalls() []struct {
	Name    string
	Options *v1.DeleteOptions
} {
	var calls []struct {
		Name    string
		Options *v1.DeleteOptions
	}
	lockEventInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockEventInterfaceMockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *EventInterfaceMock) DeleteCollection(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("EventInterfaceMock.DeleteCollectionFunc: method is nil but EventInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}{
		DeleteOpts: deleteOpts,
		ListOpts:   listOpts,
	}
	lockEventInterfaceMockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	lockEventInterfaceMockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(deleteOpts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedEventInterface.DeleteCollectionCalls())
func (mock *EventInterfaceMock) DeleteCollectionCalls() []struct {
	DeleteOpts *v1.DeleteOptions
	ListOpts   v1.ListOptions
} {
	var calls []struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}
	lockEventInterfaceMockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	lockEventInterfaceMockDeleteCollection.RUnlock()
	return calls
}

// DeleteNamespaced calls DeleteNamespacedFunc.
func (mock *EventInterfaceMock) DeleteNamespaced(namespace string, name string, options *v1.DeleteOptions) error {
	if mock.DeleteNamespacedFunc == nil {
		panic("EventInterfaceMock.DeleteNamespacedFunc: method is nil but EventInterface.DeleteNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}{
		Namespace: namespace,
		Name:      name,
		Options:   options,
	}
	lockEventInterfaceMockDeleteNamespaced.Lock()
	mock.calls.DeleteNamespaced = append(mock.calls.DeleteNamespaced, callInfo)
	lockEventInterfaceMockDeleteNamespaced.Unlock()
	return mock.DeleteNamespacedFunc(namespace, name, options)
}

// DeleteNamespacedCalls gets all the calls that were made to DeleteNamespaced.
// Check the length with:
//     len(mockedEventInterface.DeleteNamespacedCalls())
func (mock *EventInterfaceMock) DeleteNamespacedCalls() []struct {
	Namespace string
	Name      string
	Options   *v1.DeleteOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}
	lockEventInterfaceMockDeleteNamespaced.RLock()
	calls = mock.calls.DeleteNamespaced
	lockEventInterfaceMockDeleteNamespaced.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *EventInterfaceMock) Get(name string, opts v1.GetOptions) (*v1.Event, error) {
	if mock.GetFunc == nil {
		panic("EventInterfaceMock.GetFunc: method is nil but EventInterface.Get was just called")
	}
	callInfo := struct {
		Name string
		Opts v1.GetOptions
	}{
		Name: name,
		Opts: opts,
	}
	lockEventInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockEventInterfaceMockGet.Unlock()
	return mock.GetFunc(name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedEventInterface.GetCalls())
func (mock *EventInterfaceMock) GetCalls() []struct {
	Name string
	Opts v1.GetOptions
} {
	var calls []struct {
		Name string
		Opts v1.GetOptions
	}
	lockEventInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockEventInterfaceMockGet.RUnlock()
	return calls
}

// GetNamespaced calls GetNamespacedFunc.
func (mock *EventInterfaceMock) GetNamespaced(namespace string, name string, opts v1.GetOptions) (*v1.Event, error) {
	if mock.GetNamespacedFunc == nil {
		panic("EventInterfaceMock.GetNamespacedFunc: method is nil but EventInterface.GetNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}{
		Namespace: namespace,
		Name:      name,
		Opts:      opts,
	}
	lockEventInterfaceMockGetNamespaced.Lock()
	mock.calls.GetNamespaced = append(mock.calls.GetNamespaced, callInfo)
	lockEventInterfaceMockGetNamespaced.Unlock()
	return mock.GetNamespacedFunc(namespace, name, opts)
}

// GetNamespacedCalls gets all the calls that were made to GetNamespaced.
// Check the length with:
//     len(mockedEventInterface.GetNamespacedCalls())
func (mock *EventInterfaceMock) GetNamespacedCalls() []struct {
	Namespace string
	Name      string
	Opts      v1.GetOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}
	lockEventInterfaceMockGetNamespaced.RLock()
	calls = mock.calls.GetNamespaced
	lockEventInterfaceMockGetNamespaced.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *EventInterfaceMock) List(opts v1.ListOptions) (*EventList, error) {
	if mock.ListFunc == nil {
		panic("EventInterfaceMock.ListFunc: method is nil but EventInterface.List was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockEventInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockEventInterfaceMockList.Unlock()
	return mock.ListFunc(opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedEventInterface.ListCalls())
func (mock *EventInterfaceMock) ListCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockEventInterfaceMockList.RLock()
	calls = mock.calls.List
	lockEventInterfaceMockList.RUnlock()
	return calls
}

// ObjectClient calls ObjectClientFunc.
func (mock *EventInterfaceMock) ObjectClient() *objectclient.ObjectClient {
	if mock.ObjectClientFunc == nil {
		panic("EventInterfaceMock.ObjectClientFunc: method is nil but EventInterface.ObjectClient was just called")
	}
	callInfo := struct {
	}{}
	lockEventInterfaceMockObjectClient.Lock()
	mock.calls.ObjectClient = append(mock.calls.ObjectClient, callInfo)
	lockEventInterfaceMockObjectClient.Unlock()
	return mock.ObjectClientFunc()
}

// ObjectClientCalls gets all the calls that were made to ObjectClient.
// Check the length with:
//     len(mockedEventInterface.ObjectClientCalls())
func (mock *EventInterfaceMock) ObjectClientCalls() []struct {
} {
	var calls []struct {
	}
	lockEventInterfaceMockObjectClient.RLock()
	calls = mock.calls.ObjectClient
	lockEventInterfaceMockObjectClient.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *EventInterfaceMock) Update(in1 *v1.Event) (*v1.Event, error) {
	if mock.UpdateFunc == nil {
		panic("EventInterfaceMock.UpdateFunc: method is nil but EventInterface.Update was just called")
	}
	callInfo := struct {
		In1 *v1.Event
	}{
		In1: in1,
	}
	lockEventInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockEventInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(in1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedEventInterface.UpdateCalls())
func (mock *EventInterfaceMock) UpdateCalls() []struct {
	In1 *v1.Event
} {
	var calls []struct {
		In1 *v1.Event
	}
	lockEventInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockEventInterfaceMockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *EventInterfaceMock) Watch(opts v1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("EventInterfaceMock.WatchFunc: method is nil but EventInterface.Watch was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockEventInterfaceMockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	lockEventInterfaceMockWatch.Unlock()
	return mock.WatchFunc(opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedEventInterface.WatchCalls())
func (mock *EventInterfaceMock) WatchCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockEventInterfaceMockWatch.RLock()
	calls = mock.calls.Watch
	lockEventInterfaceMockWatch.RUnlock()
	return calls
}
